export const GET_CANDIDATE_SCRAPED:string = 'GET_CANDIDATE_SCRAPED';
export const GET_CANDIDATE_FROM_BACK:string = 'GET_CANDIDATE_FROM_BACK';
export const GET_CANDIDATE_FROM_BACK_SUCCESS:string = 'GET_CANDIDATE_FROM_BACK_SUCCESS';
export const GET_CANDIDATE_FROM_BACK_ERROR:string = 'GET_CANDIDATE_FROM_BACK_ERROR';
export const GET_CANDIDATE_MESSAGES:string = 'GET_CANDIDATE_MESSAGES';
export const GET_CANDIDATE_MESSAGES_SUCCESS:string = 'GET_CANDIDATE_MESSAGES_SUCCESS';
export const GET_CANDIDATE_MESSAGES_ERROR:string = 'GET_CANDIDATE_MESSAGES_ERROR';